dist: xenial
language: python
python:
- '3.5'
- '3.6'
- '3.7'
install:
- pip install -r requirements.txt
script:
- pytest
deploy:
  provider: pypi
  user: iosdevlog
  on:
    python: 3.7
    tags: true
    branch: master
  distributions: sdist bdist_wheel
  skip_cleanup: true
  password:
    secure: FkBUxg0gbvQ9sIkX8SelUjCImIfjpzNFzUgiVBS785Cpj4T4WKkD0mRGLGpjiljs2mvfrcWi2oj9NFbzdkYUggSPZVMdKfb8IydGBJJzdzJBjHEFJpR72gwYQac/EbAkQqb0jeAKZL86kb5zK2AGYtQ7wfLRP454Hcf/3DaAy24d8WVSem5H5XOEnCIouxTvald08NUWL8dDPG+mu+81A22zcuOgQM/S4AR6+wIGaolSOvh/m5CkfVuU+FQnei52+y7u5tohuSWkaCFmEh09DdtBReDSH3ReA4e65SlL/2LeTvHJR84hYz8HFfyppkPAQSWCVtHfiCSFns6GdAeCieaXPcN+QvGEQxS85/0AHUXzahTDiRg411AI4AIGBruc49Rc05LA74+xKn2TTCagdnLFP4CjAGu7HJp5s9B1MenAWrA/RB7Alqc6voe7OXSq7UUnnIhZAXlc1wTORo1HSt0qnsHXAk4lzcm3bf4BJ9aahOU7m1qMdiJzPMYQx/oqJ6UcaxgWw0raEZAnaTEyjVtvQnMnt4lCJ9ih+WzyudVtyJ5nIXASyUMlXDLeLd633UExYiQc705soAnFUjE/FV6OxuX9kDdUPrarPudnPI++ZQ/RKg9zJu4uCiFaV7Xv84Kp+MRJIeiNvyemrxOdUyJggHau3hP6vFk7H6UysOA=
